import {
  homeOutline,
  flameOutline,
  logoJavascript,
  logoReact,
  musicalNotesOutline,
  schoolOutline,
  discOutline,
  filmOutline,
  gameControllerOutline,
  pulseOutline,
  footballOutline,
  sparklesOutline,
  diamondOutline,
} from 'ionicons/icons';

export const categories = [
  {
    icon: homeOutline,
    name: 'Home',
  },
  { icon: flameOutline, name: 'Trending' },
  { icon: homeOutline, name: 'Coding' },
  { icon: logoJavascript, name: 'Javascript' },
  { icon: logoReact, name: 'ReactJS' },
  { icon: musicalNotesOutline, name: 'Music' },
  { icon: schoolOutline, name: 'Education' },
  { icon: discOutline, name: 'Podcast' },
  { icon: filmOutline, name: 'Movie' },
  { icon: gameControllerOutline, name: 'Gaming' },
  { icon: pulseOutline, name: 'Live' },
  { icon: footballOutline, name: 'Sport' },
  { icon: sparklesOutline, name: 'Fashion' },
  { icon: diamondOutline, name: 'Beauty' },
];
